### PR TITLE
Allow Statement.bindParam() to accept an array of values

### PR DESCRIPTION
**Pull request by abmusse**
See issue #34

### CODE REVIEW

**Comment by abmusse** [comment]
@kadler 

Currently `statement.bind()` is simply an alias for `statement.bindParams()` These changes will cause the behavior of `statement.bind()` to change while keeping the existing behavior in `statement.bindParams()`.

**Comment by kadler** [comment]
How long has the `bind` alias existed? Is it only in development/beta code, or has it been there for a while?

**Comment by abmusse** [comment]
@kadler 

Its been there for a while. We may need to bump the major version number if we change its behavior.

**Comment by kadler** [comment]
@abmusse Is there a way we could have the user opt in to the change? Like a connection/statement option they enable? Then at the new major version, we could force users to opt-out instead and eventually remove the old method.

**Comment by kadler** [comment]
@abmusse can you clean up the conflicts?

**Comment by abmusse** [comment]
> @abmusse Is there a way we could have the user opt in to the change? Like a connection/statement option they enable? Then at the new major version, we could force users to opt-out instead and eventually remove the old method.

I have added an optional options object to `bindParam` allowing the user to enable passing an array of values. This would be done with `statement.bindParam(params, { setupParams: true });` for now. That way users would be able to opt in to this change.

This latest push has resolved the conflicts too.

**Comment by abmusse** [comment]
Also I see that this PR would land in  `master`. There is a `1.1.0` branch that was created after this PR was initially opened. I would like this change to land there first therefore I may need to open a new PR and close this one out.

**Comment by abmusse** [comment]
Closed In favor of #70

**Pull request closed without merging**
